# This Docker Compose is intended for development, therefore it loads the code directories into the container.
services:
  server:
    build:
      context: .
      target: dev
    volumes:
      - type: bind
        source: ./app/
        # Yes, really - we're using `/app` as the WD within the container, but `uvicorn` requires an import path.
        target: /app/app
    ports:
      - 8000:8000

